name: deployment pipeline for production
on:
  push:
    branches:
      - production

jobs:
  build_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Build using Parcel
        run: |
          npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./"

      - name: Saving artifact on cloud
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"
          name: "production-artifact"

  deploy_job:
    needs: build_job
    permissions:
      pages: write
      id-token: write
    environment: "production-env"
    runs-on: ubuntu-latest

    steps:
      - name: Deploy the build artifacts on GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "production-artifact"
          token: ${{ secrets.GITHUB_TOKEN }}